spring.application.name=ControleDeExame


Spring.datasource.url=${SPRING_DATASOURCE_URL:teste}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:teste}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:teste}

api.id.cid= ${ID_CLIENT_CID:adasdsa}
api.secret.cid= ${SECRET_CLIENT_CID:asdasd}

api.security.token.secret=${JWT_SECRET:my-secret-key}

api.key.mailGrid = ${API_KEY:adasdasd}






